//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AppIm.Droid.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IM_APPSoap", Namespace="http://tempuri.org/")]
    public partial class IM_APP : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InteligenciaAduanasOperationCompleted;
        
        private System.Threading.SendOrPostCallback InteligenciaEmpresasOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public IM_APP() {
            this.Url = "http://179.50.16.169/IMWS/IM_APP.ASMX";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InteligenciaAduanasCompletedEventHandler InteligenciaAduanasCompleted;
        
        /// <remarks/>
        public event InteligenciaEmpresasCompletedEventHandler InteligenciaEmpresasCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InteligenciaAduanas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable InteligenciaAduanas(string cNit, string dFechaInicial, string dFechaFinal, string cTipo) {
            object[] results = this.Invoke("InteligenciaAduanas", new object[] {
                        cNit,
                        dFechaInicial,
                        dFechaFinal,
                        cTipo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void InteligenciaAduanasAsync(string cNit, string dFechaInicial, string dFechaFinal, string cTipo) {
            this.InteligenciaAduanasAsync(cNit, dFechaInicial, dFechaFinal, cTipo, null);
        }
        
        /// <remarks/>
        public void InteligenciaAduanasAsync(string cNit, string dFechaInicial, string dFechaFinal, string cTipo, object userState) {
            if ((this.InteligenciaAduanasOperationCompleted == null)) {
                this.InteligenciaAduanasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInteligenciaAduanasOperationCompleted);
            }
            this.InvokeAsync("InteligenciaAduanas", new object[] {
                        cNit,
                        dFechaInicial,
                        dFechaFinal,
                        cTipo}, this.InteligenciaAduanasOperationCompleted, userState);
        }
        
        private void OnInteligenciaAduanasOperationCompleted(object arg) {
            if ((this.InteligenciaAduanasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InteligenciaAduanasCompleted(this, new InteligenciaAduanasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InteligenciaEmpresas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable InteligenciaEmpresas(string cNit, string dFechaInicial, string dFechaFinal, string cTipo) {
            object[] results = this.Invoke("InteligenciaEmpresas", new object[] {
                        cNit,
                        dFechaInicial,
                        dFechaFinal,
                        cTipo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void InteligenciaEmpresasAsync(string cNit, string dFechaInicial, string dFechaFinal, string cTipo) {
            this.InteligenciaEmpresasAsync(cNit, dFechaInicial, dFechaFinal, cTipo, null);
        }
        
        /// <remarks/>
        public void InteligenciaEmpresasAsync(string cNit, string dFechaInicial, string dFechaFinal, string cTipo, object userState) {
            if ((this.InteligenciaEmpresasOperationCompleted == null)) {
                this.InteligenciaEmpresasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInteligenciaEmpresasOperationCompleted);
            }
            this.InvokeAsync("InteligenciaEmpresas", new object[] {
                        cNit,
                        dFechaInicial,
                        dFechaFinal,
                        cTipo}, this.InteligenciaEmpresasOperationCompleted, userState);
        }
        
        private void OnInteligenciaEmpresasOperationCompleted(object arg) {
            if ((this.InteligenciaEmpresasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InteligenciaEmpresasCompleted(this, new InteligenciaEmpresasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Login(string Usuario, string Pass) {
            object[] results = this.Invoke("Login", new object[] {
                        Usuario,
                        Pass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string Usuario, string Pass) {
            this.LoginAsync(Usuario, Pass, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string Usuario, string Pass, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        Usuario,
                        Pass}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void InteligenciaAduanasCompletedEventHandler(object sender, InteligenciaAduanasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InteligenciaAduanasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InteligenciaAduanasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void InteligenciaEmpresasCompletedEventHandler(object sender, InteligenciaEmpresasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InteligenciaEmpresasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InteligenciaEmpresasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591